# Railway Configuration
# This file tells Railway how to deploy the services

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - NODE_ENV=production
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  ai-engine:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
