# Railway Configuration
# This file tells Railway how to deploy the services

services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  ai-engine:
    build:
      context: ai_engine
      dockerfile: Dockerfile
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
